# Generated by Django 5.2.8 on 2025-12-18 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(default='book', max_length=50)),
                ('cor', models.CharField(default='#FFD700', max_length=7)),
                ('dificuldade', models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('tempo_estimado', models.IntegerField(default=0)),
                ('pontos_recompensa', models.IntegerField(default=100)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trilha',
                'verbose_name_plural': 'Trilhas',
                'ordering': ['ordem', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('conteudo', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('ordem', models.IntegerField(default=0)),
                ('duracao', models.IntegerField(default=0)),
                ('concluido', models.BooleanField(default=False)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='trilhas.trilha')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='ProgressoTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_concluido', models.FloatField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('modulo_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_trilhas', to=settings.AUTH_USER_MODEL)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.trilha')),
            ],
            options={
                'verbose_name': 'Progresso de Trilha',
                'verbose_name_plural': 'Progressos de Trilhas',
                'unique_together': {('usuario', 'trilha')},
            },
        ),
    ]
