# Generated by Django 5.2.8 on 2025-12-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo_html', models.TextField()),
                ('ordem', models.IntegerField(default=0)),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='trilhas.trilha')),
            ],
        ),
    ]
