# Generated by Django 5.2.8 on 2025-12-07 01:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trilhas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['ordem'], 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={'ordering': ['ordem', 'data_criacao'], 'verbose_name': 'Trilha', 'verbose_name_plural': 'Trilhas'},
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='conteudo_html',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='trilha',
            old_name='ativa',
            new_name='ativo',
        ),
        migrations.AddField(
            model_name='modulo',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='modulo',
            name='conteudo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modulo',
            name='duracao',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modulo',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='trilha',
            name='cor',
            field=models.CharField(default='#FFD700', max_length=7),
        ),
        migrations.AddField(
            model_name='trilha',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trilha',
            name='dificuldade',
            field=models.CharField(choices=[('iniciante', 'Iniciante'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20),
        ),
        migrations.AddField(
            model_name='trilha',
            name='icone',
            field=models.CharField(default='book', max_length=50),
        ),
        migrations.AddField(
            model_name='trilha',
            name='pontos_recompensa',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='trilha',
            name='tempo_estimado',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProgressoTrilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual_concluido', models.FloatField(default=0)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('modulo_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trilhas.modulo')),
                ('trilha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trilhas.trilha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresso_trilhas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progresso de Trilha',
                'verbose_name_plural': 'Progressos de Trilhas',
                'unique_together': {('usuario', 'trilha')},
            },
        ),
    ]
