# Generated by Django 5.2.8 on 2025-12-18 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jornada_iniciada', models.BooleanField(default=False)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('nivel', models.IntegerField(default=1)),
                ('xp', models.IntegerField(default=0)),
                ('trilhas_concluidas', models.IntegerField(default=0)),
                ('exercicios_resolvidos', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='LinkSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('website', 'Website Pessoal'), ('portfolio', 'Portfólio'), ('youtube', 'YouTube'), ('facebook', 'Facebook'), ('outro', 'Outro')], max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_sociais', to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Link Social',
                'verbose_name_plural': 'Links Sociais',
                'ordering': ['ordem', 'data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='AtividadePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('login', 'Login'), ('trilha', 'Trilha'), ('exercicio', 'Exercício'), ('perfil', 'Perfil'), ('conquista', 'Conquista'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='usuarios.perfil')),
            ],
            options={
                'verbose_name': 'Atividade de Perfil',
                'verbose_name_plural': 'Atividades de Perfil',
                'ordering': ['-data'],
            },
        ),
    ]
