# Generated by Django 5.2.8 on 2025-12-07 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='exercicios_resolvidos',
            field=models.ManyToManyField(blank=True, related_name='resolvido_por', to='exercicios.exercicio'),
        ),
    ]
