# Generated by Django 5.2.8 on 2025-12-18 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trilhas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('enunciado', models.TextField()),
                ('codigo_inicial', models.TextField(blank=True)),
                ('resposta_correta', models.TextField()),
                ('pontos', models.IntegerField(default=10)),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], max_length=20)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios', to='trilhas.modulo')),
            ],
        ),
    ]
