# Generated by Django 5.2.8 on 2025-12-19 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('correto', 'Correto'), ('incorreto', 'Incorreto'), ('parcial', 'Parcialmente Correto')], default='pendente', max_length=20)),
                ('tentativas', models.IntegerField(default=1)),
                ('pontos_ganhos', models.IntegerField(default=0)),
                ('tempo_gasto', models.IntegerField(default=0, help_text='Tempo gasto em segundos')),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_exercicios', to=settings.AUTH_USER_MODEL)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='exercicios.exercicio')),
            ],
            options={
                'verbose_name': 'Resposta do Aluno',
                'verbose_name_plural': 'Respostas dos Alunos',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
